name: Upload Crowdin files

# on any push to main, we upload the translations to be translated
on:
  push:
    branches:
      - main

jobs:
  upload-to-crowdin:
    name: Upload sources to Crowdin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.0

      - uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a # v3.0.0
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Synchronize
        uses: crowdin/github-action@9237b4cb361788dfce63feb2e2f15c09e2fe7415 # v1.4.7
        with:
          upload_sources: true
          download_translations: false
          config: 'crowdin.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
