name: Upload Crowdin files

# on any push to main, we upload the translations to be translated
on:
  push:
    branches:
      - main

jobs:
  upload-to-crowdin:
    name: Upload sources to Crowdin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # v3.4.1
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Synchronize
        uses: crowdin/github-action@8461edd493435e3f838de2f81301f093aed04e51 # v1.4.12
        with:
          upload_sources: true
          download_translations: false
          config: 'crowdin.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
